name: notas_animo
description: App de notas de ánimo
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dynamic_color: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
