name: notas_animo
description: App de notas de ánimo
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dynamic_color: ^1.7.0
  uuid: ^4.3.3
  flutter_staggered_animations: ^1.1.1
  flutter_hooks: ^0.21.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  crypto: ^3.0.3
  email_validator: ^2.1.17
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
