name: notas_animo
description: App de notas de ánimo
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  crypto: ^3.0.3
  sqflite: ^2.3.2
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  image: ^4.1.7
  email_validator: ^2.1.17
  flutter_secure_storage: ^9.0.0
  path_provider_android: ^2.0.27
  dynamic_color: ^1.7.0
  uuid: ^4.3.3
  flutter_staggered_animations: ^1.1.1
  flutter_hooks: ^0.21.2
  table_calendar: ^3.0.9
  flutter_animate: ^4.2.0
  camera: ^0.10.5+3
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  mime: ^1.0.3
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/icon/icon.png"
  windows:
    generate: true
    image_path: "lib/assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/
